### ISSUE TITLE
Missing Talents?

### ISSUE THREAD

**Issue by pandon101** [Dimencia/DU-Industry-Tool#1]
You are missing Intermediary Parts Productivity, Basic, uncommon and advanced. This will add +1 per level so +5 items per craft time. This should correct the issue I see in Pricing.

**Comment by Dimencia** [comment]
They are there in the latest releases.  You will need to make sure to delete the old talentSettings.json so it can generate a new one that contains the talents.  But... they've been there since the first ones, they're just hard to find until I alphabetized them in recent

**Comment by pandon101** [comment]
I see it now.. Can you verify the price on basic pipes.. I'm getting a lower cost then you have here.. and not sure how., I must have missed something.. too tired. will verify and see if I can find issue.

**Comment by Dimencia** [comment]
My best source of verification is a second spreadsheet I made, so.... I don't have a lot to compare to.  But as far as I can tell everything matches identically.  I did struggle for a very long time thinking it was wrong - only to find that I had missed an important skill.  
I'll work on categorizing those so they're not quite so painful

But, even if you're not familiar with C#, I would love it if you could look over what I have for talents.  I think everything should be relatively self explanatory, with comments and etc.  Start here, with how I define them
https://github.com/Dimencia/DU-Industry-Tool/blob/6d042c66caf84592f26ae57e356c27e620f31c68/DU%20Industry%20Tool/IndustryManager.cs#L134

And then here with how I use them and calculate costs
https://github.com/Dimencia/DU-Industry-Tool/blob/6d042c66caf84592f26ae57e356c27e620f31c68/DU%20Industry%20Tool/IndustryManager.cs#L326

The second one's a bit rough being recursive but, you can probably get the gist of what I'm doing and let me know if I missed anything or anything's obviously wrong on the first one at least

**Comment by Dimencia** [comment]
I've pushed an updated version with better comments that should be easier to look over, if you're so inclined.  The relevant parts are at
https://github.com/Dimencia/DU-Industry-Tool/blob/a9cbcbaed4d498320ff0f65e8dc4bb909f2a0f61/DU%20Industry%20Tool/IndustryManager.cs#L77 
and
https://github.com/Dimencia/DU-Industry-Tool/blob/a9cbcbaed4d498320ff0f65e8dc4bb909f2a0f61/DU%20Industry%20Tool/IndustryManager.cs#L256

**Comment by pandon101** [comment]
I found my issue. This looks very good. Thank you for the work you have done.
Please keep this updated as we get new changes.
