### ISSUE TITLE
material Quantity issue

### ISSUE THREAD

**Issue by pandon101** [Dimencia/DU-Industry-Tool#15]
Example:
T1 Silumin Product:               10,000.00 L

For 1 Basic Container L?

looks to be about 10x 1 Basic Container L uses about 1,050 Liters

**Comment by pandon101** [comment]
Cost for 1 Basic Container l
Item schematic(s) T1EL: 15,000.0q

Ores
T1 Bauxite:                       27,579.26 L
T1 Coal:                           5,481.67 L
T1 Hematite:                      14,232.59 L
T1 Quartz:                        21,666.67 L
Pures
T1 Pure Aluminium:                19,093.33 L
T1 Pure Carbon:                    3,795.00 L
T1 Pure Iron:                      9,853.33 L
T1 Pure Silicon:                  15,000.00 L
---
should be more like:
Bauxite
2,925.00

Hematite
5,850.00

Coal
2,925.00

Quartz
1,170.00

**Comment by CCGLLC-knc** [comment]
Per another player without github access:  It appears the number of products per batch is not being factored in.  Thus is a batch produces 10 products, its off by 10X

**Comment by OwenQuillion** [comment]
The program seems to be dividing Output by Input, which is the wrong way around. 

With no talents, you use 65 Ore to get 45 Pure, so a Pure obviously has to cost >1 ore. The tool reports that a Pure costs 0.69 Ore. It should actually be 65/45, for a cost of 1.44 Ore per Pure. 

If you go up one level to a Product, you'll see that Silumin takes 100 Aluminum and 50 Silicon as input, but it somehow costs *less* Bauxite than Quartz. Apparently the program is taking 75 product / (100*0.69 ore) to get 1.08 units of Bauxite, and the same for the 50 units of Silicon to get to 2.17 Quartz. 

If the program does that at every step, it's no wonder that the results become pretty distorted by the end.

**Comment by tobitege** [comment]
> Example: T1 Silumin Product: 10,000.00 L
> 
> For 1 Basic Container L?
> 
> looks to be about 10x 1 Basic Container L uses about 1,050 Liters
@OwenQuillion and @pandon101 :
Thanks for the reports. I'll look into those errors in the coming days.

**Comment by Dimencia** [comment]
Fixed as of 0.7.7
