### ISSUE TITLE
DocumentFormat.OpenXml Version Mismatch

### ISSUE THREAD

**Issue by jcp219** [Dimencia/DU-Industry-Tool#17]
Getting a DLL version mismatch on DocumentFormat.OpenXml. The included assembly is version 2.17 while the referenced assembly is 2.16.

![image](https://user-images.githubusercontent.com/13525083/188505793-77bf1a16-ae39-4adf-9e22-00ec90e5873a.png)

**Comment by Dimencia** [comment]
Issue fixed as of 0.7.7
