### ISSUE TITLE
The v0.25 binary from the releases page is missing the Factory Breakdown for Selected option

### ISSUE THREAD

**Issue by ghost** [Dimencia/DU-Industry-Tool#2]
It looks like the v0.25 release binary may have been built from a previous version of the code. The release note says that the Factory Export is available, but I don't see it under settings. Screenshot attached.

When I clone the repo and build in Visual Studio I do see the option, so I think the release is just outdated.
![du-industry-0 25-issue](https://user-images.githubusercontent.com/79300843/108467400-fe4b9280-7239-11eb-91bf-2dbb9df24d0c.png)

**Comment by Dimencia** [comment]
Probably was, didn't notice.  Should be better in the most recent release.
