### ISSUE TITLE
0.8.0 Unhandled exception

### ISSUE THREAD

**Issue by CCGLLC-knc** [Dimencia/DU-Industry-Tool#20]
Screen capture with details:

http://puu.sh/Jl24u/26791ef81e.png

Reproducible at launch, and when attempting to switch themes.

ps.  Thanks for creating this!!!

**Comment by tobitege** [comment]
Thanks for the report!
I fixed the issue in v0.8.1, you can download it from my repo for now:
https://github.com/tobitege/DU-Industry-Tool/releases/tag/v0.8.1

**Comment by CCGLLC-knc** [comment]
Thanks for the rapid fix and direct link!
