### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by Sambo726** [Dimencia/DU-Industry-Tool#4]
Missing some Advanced and Rare engine types. (Maneuver)
![image](https://user-images.githubusercontent.com/75092566/119886316-d470ce80-bf00-11eb-9fce-17ecd38482d8.png)

**Comment by Dimencia** [comment]
The project is no longer being maintained.  Those can be added manually or through the procedure that is now described in the readme, if anyone is interested in adding them
