### ISSUE TITLE
New Items need added for Demeter Update

### ISSUE THREAD

**Issue by pandon101** [Dimencia/DU-Industry-Tool#5]
Please add mining units to this Utility.

**Comment by pandon101** [comment]
Will this utility be updated?

**Comment by Dimencia** [comment]
It will not be updated and is not actively maintained.  I've lost the old lua and C# that handled the merging of data into RecipesGroups.json but it is ... sorta straightforward.

Anyone could add the mining units, it's just a json file.  Either add the new stuff manually, or:
1. Do a hyperion export of all item NqRecipeId's for all items (particularly the new ones), along with Name
2. Create a lua script to run core.getSchematicInfo(id) for every NqRecipeId.  Store all the data it gives you, and export it to json
3. Do a hyperion export of all item Groups (it's a separate category in lua export), the GroupId and ParentGroupId (see: Groups.json in this repo, but there may be new ones)
4. Using any language, lua or out of game at this point, load the recipe info json file, along with the Groups json file, and combine them.  Add fields as necessary to the recipe data to match the 'SchematicRecipe' class in Recipe.cs, such as 'Name', 'GroupId', and 'ParentGroupName' (Key doesn't need to exist and/or should be null).  I think those three vars are the only thing different from core.getSchematicInfo's output
